package dbmd;



import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import dbmd.ModeloTabela;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marlon Prudente <marlonmateuspr@gmail.com>
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Connection con;
    DatabaseMetaData metadata;
    Integer indice = 0;
    public Main() {
        
    
        initComponents();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");  
        }
        catch (ClassNotFoundException al){
            System.out.println("Driver não encontrado");
            System.exit(0);
        }
        try{
        String url = "jdbc:mysql://100.43.1.76/livraria";
        String user = "root";
        String passwd = "mpo121991";
        con = DriverManager.getConnection(url, user, passwd);
        metadata = con.getMetaData();
    }catch(SQLException sql1){
            System.out.println("Erro de Conexão");
            System.exit(0);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        nometabela = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        anterior = new javax.swing.JButton();
        proximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome da Tabela:");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        jLabel2.setText("Propriedades das Colunas:");

        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        proximo.setText("Próximo");
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nometabela))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(proximo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nometabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar)
                    .addComponent(anterior)
                    .addComponent(proximo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        navegarTabela(0);
        /*String table[] = {"TABLE"};
        ResultSet rs = null;
        ArrayList tables = null;        
        try {
        rs = metadata.getTables(null, null, null, table);
        tables = new ArrayList();        
            while(rs.next()){
                tables.add(rs.getString("TABLE_NAME"));                                      
               }
           String namet = (String) tables.get(0);
            rs = metadata.getColumns(null, null, namet, null);           
            nometabela.setText(namet.toUpperCase());           
        String colunas[] = {"NOME", "TIPO", "TAMANHO"};
         Object dados[][] = new Object[3][tables.size()];
         int count = 0;
         while(rs.next()){
             dados[count][0] = rs.getString("COLUMN_NAME");
             dados[count][1] = rs.getString("TYPE_NAME");
             dados[count][2] = rs.getString("COLUMN_SIZE");
             count++;
         }
        tabela = new JTable(dados, colunas);
        jScrollPane1.setViewportView(tabela);
            
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }  */
    }//GEN-LAST:event_buscarActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        if(indice !=0){
            indice--;
            navegarTabela(indice);
        }
        else{
            navegarTabela(indice);
        }

    // TODO add your handling code here:
    }//GEN-LAST:event_anteriorActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        // TODO add your handling code here:
          if(indice <4){
            indice++;
            navegarTabela(indice);
        }
        else{
            navegarTabela(indice);
        }
    }//GEN-LAST:event_proximoActionPerformed

    /**
     *
     */
    public  void navegarTabela(Integer indice){
        String table[] = {"TABLE"};
        ResultSet rs = null;
        ArrayList tables = null;        
        try {
        rs = metadata.getTables(null, null, null, table);
        tables = new ArrayList();        
            while(rs.next()){
                tables.add(rs.getString("TABLE_NAME"));                                      
               }
           String namet = (String) tables.get(indice);
            rs = metadata.getColumns(null, null, namet, null);           
            nometabela.setText(namet.toUpperCase());           
        String colunas[] = {"NOME", "TIPO", "TAMANHO"};
         Object dados[][] = new Object[20][20];
         int count = 0;
         while(rs.next()){
             dados[count][0] = rs.getString("COLUMN_NAME");
             dados[count][1] = rs.getString("TYPE_NAME");
             dados[count][2] = rs.getString("COLUMN_SIZE");
             count++;
         }
        tabela = new JTable(dados, colunas);
        jScrollPane1.setViewportView(tabela);
        
    }catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nometabela;
    private javax.swing.JButton proximo;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
